-- MySQL Script generated by MySQL Workbench
-- พ. 11 ธ.ค. 2562, 12:54:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mfu-coffee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mfu-coffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mfu-coffee` ;
USE `mfu-coffee` ;

-- -----------------------------------------------------
-- Table `mfu-coffee`.`roaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfu-coffee`.`roaster` (
  `roasterid` INT NOT NULL,
  `roastername` VARCHAR(140) NULL,
  `roasterlocation` VARCHAR(140) NULL,
  `roasterdetails` VARCHAR(280) NULL,
  PRIMARY KEY (`roasterid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfu-coffee`.`coffee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfu-coffee`.`coffee` (
  `coffeeid` INT NOT NULL,
  `coffeename` VARCHAR(140) NULL,
  `coffeeorigin` VARCHAR(140) NULL,
  `coffeevariety` VARCHAR(140) NULL,
  `roaster_roasterid` INT NOT NULL,
  PRIMARY KEY (`coffeeid`),
  INDEX `fk_coffee_roaster_idx` (`roaster_roasterid` ASC) VISIBLE,
  CONSTRAINT `fk_coffee_roaster`
    FOREIGN KEY (`roaster_roasterid`)
    REFERENCES `mfu-coffee`.`roaster` (`roasterid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfu-coffee`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfu-coffee`.`user` (
  `userid` INT NOT NULL,
  `username` VARCHAR(35) NULL,
  `useravatar` VARCHAR(280) NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfu-coffee`.`flavorchart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfu-coffee`.`flavorchart` (
  `flavorid` INT NOT NULL,
  `flavorname` VARCHAR(140) NULL,
  PRIMARY KEY (`flavorid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfu-coffee`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfu-coffee`.`rating` (
  `ratingid` INT NOT NULL,
  `ratingnotes` VARCHAR(280) NULL,
  `ratingscore` INT NULL,
  `ratingdate` DATETIME NULL,
  `coffee_coffeeid` INT NOT NULL,
  `user_userid` INT NOT NULL,
  `flavorchart_flavorid` INT NOT NULL,
  PRIMARY KEY (`ratingid`),
  INDEX `fk_rating_coffee1_idx` (`coffee_coffeeid` ASC) VISIBLE,
  INDEX `fk_rating_user1_idx` (`user_userid` ASC) VISIBLE,
  INDEX `fk_rating_flavorchart1_idx` (`flavorchart_flavorid` ASC) VISIBLE,
  CONSTRAINT `fk_rating_coffee1`
    FOREIGN KEY (`coffee_coffeeid`)
    REFERENCES `mfu-coffee`.`coffee` (`coffeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `mfu-coffee`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_flavorchart1`
    FOREIGN KEY (`flavorchart_flavorid`)
    REFERENCES `mfu-coffee`.`flavorchart` (`flavorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
